// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  guideSidebar: [
    {
      type: 'category',
      label: '目次',
      items: [
        'guide/LetsStart', 
        {
          type: 'category',
          label: 'ジェスチャー演奏モード',
          items: [
            'guide/Gesture_Playing_Mode/Start_StopPlaying', 'guide/Gesture_Playing_Mode/Select_an_instrument','guide/Gesture_Playing_Mode/Recording',
            'guide/Gesture_Playing_Mode/Selecting_a_score',
          ],
        },
        {
          type: 'category',
          label: '自動演奏モード',
          items: ['guide/Gesture_Playing_Mode/Start_StopPlaying'],
        },
        {
          type: 'category',
          label: '手回し演奏モード',
          items: ['guide/Gesture_Playing_Mode/Start_StopPlaying'],
        },
        {
          type: 'category',
          label: '楽譜の印刷',
          items: ['guide/Gesture_Playing_Mode/Start_StopPlaying'],
        },
        {
          type: 'category',
          label: '設定',
          items: ['guide/Gesture_Playing_Mode/Start_StopPlaying'],
        },
      ],
    }
  ],
  privacySidebar: [
    {
      type: 'category',
      label: '内容',
      items: ['PrivacyPolicy'],
    }
  ],
  gallerySidebar: [
    {
      type: 'category',
      label: 'ギャラリー',
      items: ['gallery/movies'],
    }
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
