name: Deploy Docusaurus with YouTube Data

on:
  push:                   # mainにpush
    branches:
      - main
  workflow_dispatch:      # 手動実行
    inputs:
      full:
        description: 'Run full fetch?'
        required: false
        default: "false"
  #schedule:
  #  - cron: "0 6 * * *"  # ← 毎日 15:00 JST (6:00 UTC) に自動実行

permissions:
  contents: write

jobs:
  update-videos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Fetch YouTube videos
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          #node scripts/fetch_youtube.js
          node scripts/updateYoutube.js "${{ github.event.inputs.full }}"

      - name: Build Docusaurus
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages